"""fix question-answeroption relationship

Revision ID: 0ae17368c4c9
Revises: dd4430b4ae7a
Create Date: 2026-01-24 12:49:17.390713

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '0ae17368c4c9'
down_revision = 'dd4430b4ae7a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('answer_option', schema=None) as batch_op:
        batch_op.create_foreign_key(None, 'question', ['question_id'], ['question_id'])

    with op.batch_alter_table('question', schema=None) as batch_op:
        batch_op.add_column(sa.Column('image_data', sa.LargeBinary(), nullable=True))
        batch_op.create_foreign_key(None, 'answer_option', ['correct_answer_id'], ['answer_id'])
        batch_op.create_foreign_key(None, 'topic', ['topic_id'], ['topic_id'])
        batch_op.drop_column('image_url')

    with op.batch_alter_table('quiz_question', schema=None) as batch_op:
        batch_op.create_foreign_key(None, 'quiz', ['quiz_id'], ['quiz_id'])
        batch_op.create_foreign_key(None, 'question', ['question_id'], ['question_id'])

    with op.batch_alter_table('topic', schema=None) as batch_op:
        batch_op.create_foreign_key(None, 'topic', ['parent_topic'], ['topic_id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('topic', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')

    with op.batch_alter_table('quiz_question', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')

    with op.batch_alter_table('question', schema=None) as batch_op:
        batch_op.add_column(sa.Column('image_url', mysql.VARCHAR(length=500), nullable=True))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('image_data')

    with op.batch_alter_table('answer_option', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')

    # ### end Alembic commands ###
