"""make req_is nullable

Revision ID: 0bc80c3f6065
Revises: 13846e3549ab
Create Date: 2026-06-07 13:53:10.783254

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '0bc80c3f6065'
down_revision = '13846e3549ab'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('analytics_events', schema=None) as batch_op:
        batch_op.create_foreign_key(None, 'users', ['user_id'], ['id'])

    with op.batch_alter_table('answer_option', schema=None) as batch_op:
        batch_op.create_foreign_key(None, 'question', ['question_id'], ['question_id'], ondelete='CASCADE')

    with op.batch_alter_table('component_items', schema=None) as batch_op:
        batch_op.create_foreign_key(None, 'components', ['component_id'], ['component_id'])

    with op.batch_alter_table('components', schema=None) as batch_op:
        batch_op.create_foreign_key(None, 'sections', ['section_id'], ['section_id'])

    with op.batch_alter_table('question', schema=None) as batch_op:
        batch_op.create_foreign_key(None, 'answer_option', ['correct_answer_id'], ['answer_id'], ondelete='SET NULL')
        batch_op.create_foreign_key(None, 'topic', ['topic_id'], ['topic_id'], ondelete='CASCADE')

    with op.batch_alter_table('quiz_question', schema=None) as batch_op:
        batch_op.create_foreign_key(None, 'question', ['question_id'], ['question_id'])
        batch_op.create_foreign_key(None, 'quiz', ['quiz_id'], ['quiz_id'])

    with op.batch_alter_table('requests', schema=None) as batch_op:
        batch_op.create_foreign_key(None, 'subscription_plans', ['plan_id'], ['id'])
        batch_op.create_foreign_key(None, 'users', ['user_id'], ['id'])

    with op.batch_alter_table('sections', schema=None) as batch_op:
        batch_op.create_foreign_key(None, 'topic', ['topic_id'], ['topic_id'])

    with op.batch_alter_table('subscriptions', schema=None) as batch_op:
        batch_op.alter_column('req_id',
               existing_type=mysql.INTEGER(),
               nullable=True)
        batch_op.create_foreign_key(None, 'subscription_plans', ['plan_id'], ['id'])
        batch_op.create_foreign_key(None, 'requests', ['req_id'], ['id'])
        batch_op.create_foreign_key(None, 'users', ['user_id'], ['id'])

    with op.batch_alter_table('topic', schema=None) as batch_op:
        batch_op.create_foreign_key(None, 'topic', ['parent_topic'], ['topic_id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('topic', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')

    with op.batch_alter_table('subscriptions', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.alter_column('req_id',
               existing_type=mysql.INTEGER(),
               nullable=False)

    with op.batch_alter_table('sections', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')

    with op.batch_alter_table('requests', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')

    with op.batch_alter_table('quiz_question', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')

    with op.batch_alter_table('question', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')

    with op.batch_alter_table('components', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')

    with op.batch_alter_table('component_items', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')

    with op.batch_alter_table('answer_option', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')

    with op.batch_alter_table('analytics_events', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')

    # ### end Alembic commands ###
