"""mimetype

Revision ID: 0d378c43eb4d
Revises: 3956cb9a5b66
Create Date: 2026-01-29 12:02:17.002872

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '0d378c43eb4d'
down_revision = '3956cb9a5b66'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('answer_option', schema=None) as batch_op:
        batch_op.create_foreign_key(None, 'question', ['question_id'], ['question_id'])

    with op.batch_alter_table('question', schema=None) as batch_op:
        batch_op.create_foreign_key(None, 'topic', ['topic_id'], ['topic_id'])
        batch_op.create_foreign_key(None, 'answer_option', ['correct_answer_id'], ['answer_id'])

    with op.batch_alter_table('quiz_question', schema=None) as batch_op:
        batch_op.create_foreign_key(None, 'quiz', ['quiz_id'], ['quiz_id'])
        batch_op.create_foreign_key(None, 'question', ['question_id'], ['question_id'])

    with op.batch_alter_table('topic', schema=None) as batch_op:
        batch_op.create_foreign_key(None, 'topic', ['parent_topic'], ['topic_id'])

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('password',
               existing_type=mysql.VARCHAR(length=80),
               type_=sa.String(length=256),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('password',
               existing_type=sa.String(length=256),
               type_=mysql.VARCHAR(length=80),
               existing_nullable=False)

    with op.batch_alter_table('topic', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')

    with op.batch_alter_table('quiz_question', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')

    with op.batch_alter_table('question', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')

    with op.batch_alter_table('answer_option', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')

    # ### end Alembic commands ###
