"""added the cleaned_hash field to Question

Revision ID: 13846e3549ab
Revises: 0ba1bd0f3cf0
Create Date: 2026-06-06 20:19:16.767518

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '13846e3549ab'
down_revision = '0ba1bd0f3cf0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('analytics_events', schema=None) as batch_op:
        batch_op.create_foreign_key(None, 'users', ['user_id'], ['id'])

    with op.batch_alter_table('answer_option', schema=None) as batch_op:
        batch_op.create_foreign_key(None, 'question', ['question_id'], ['question_id'], ondelete='CASCADE')

    with op.batch_alter_table('component_items', schema=None) as batch_op:
        batch_op.create_foreign_key(None, 'components', ['component_id'], ['component_id'])

    with op.batch_alter_table('components', schema=None) as batch_op:
        batch_op.create_foreign_key(None, 'sections', ['section_id'], ['section_id'])

    with op.batch_alter_table('question', schema=None) as batch_op:
        batch_op.add_column(sa.Column('cleaned_hash', sa.String(length=64), nullable=True))
        batch_op.create_index(batch_op.f('ix_question_cleaned_hash'), ['cleaned_hash'], unique=True)
        batch_op.create_foreign_key(None, 'answer_option', ['correct_answer_id'], ['answer_id'], ondelete='SET NULL')
        batch_op.create_foreign_key(None, 'topic', ['topic_id'], ['topic_id'], ondelete='CASCADE')

    with op.batch_alter_table('quiz_question', schema=None) as batch_op:
        batch_op.create_foreign_key(None, 'quiz', ['quiz_id'], ['quiz_id'])
        batch_op.create_foreign_key(None, 'question', ['question_id'], ['question_id'])

    with op.batch_alter_table('requests', schema=None) as batch_op:
        batch_op.create_foreign_key(None, 'subscription_plans', ['plan_id'], ['id'])
        batch_op.create_foreign_key(None, 'users', ['user_id'], ['id'])

    with op.batch_alter_table('sections', schema=None) as batch_op:
        batch_op.create_foreign_key(None, 'topic', ['topic_id'], ['topic_id'])

    with op.batch_alter_table('subscriptions', schema=None) as batch_op:
        batch_op.create_foreign_key(None, 'subscription_plans', ['plan_id'], ['id'])
        batch_op.create_foreign_key(None, 'requests', ['req_id'], ['id'])
        batch_op.create_foreign_key(None, 'users', ['user_id'], ['id'])

    with op.batch_alter_table('topic', schema=None) as batch_op:
        batch_op.create_foreign_key(None, 'topic', ['parent_topic'], ['topic_id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('topic', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')

    with op.batch_alter_table('subscriptions', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')

    with op.batch_alter_table('sections', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')

    with op.batch_alter_table('requests', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')

    with op.batch_alter_table('quiz_question', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')

    with op.batch_alter_table('question', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_question_cleaned_hash'))
        batch_op.drop_column('cleaned_hash')

    with op.batch_alter_table('components', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')

    with op.batch_alter_table('component_items', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')

    with op.batch_alter_table('answer_option', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')

    with op.batch_alter_table('analytics_events', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')

    # ### end Alembic commands ###
