"""fix topic self reference

Revision ID: 2e0950b4f8d8
Revises: 
Create Date: 2026-01-24 12:33:45.058746

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2e0950b4f8d8'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('answer_option',
    sa.Column('answer_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('question_id', sa.Integer(), nullable=True),
    sa.Column('option_text', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['question_id'], ['question.question_id'], ),
    sa.PrimaryKeyConstraint('answer_id')
    )
    op.create_table('question',
    sa.Column('question_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('image_url', sa.String(length=500), nullable=True),
    sa.Column('topic_id', sa.Integer(), nullable=True),
    sa.Column('correct_answer_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['correct_answer_id'], ['answer_option.answer_id'], ),
    sa.ForeignKeyConstraint(['topic_id'], ['topic.topic_id'], ),
    sa.PrimaryKeyConstraint('question_id')
    )
    op.create_table('quiz',
    sa.Column('quiz_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('title', sa.String(length=255), nullable=True),
    sa.Column('publish_date', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('quiz_id')
    )
    op.create_table('topic',
    sa.Column('topic_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('parent_topic', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['parent_topic'], ['topic.topic_id'], ),
    sa.PrimaryKeyConstraint('topic_id')
    )
    op.create_table('quiz_question',
    sa.Column('quiz_id', sa.Integer(), nullable=False),
    sa.Column('question_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['question_id'], ['question.question_id'], ),
    sa.ForeignKeyConstraint(['quiz_id'], ['quiz.quiz_id'], ),
    sa.PrimaryKeyConstraint('quiz_id', 'question_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('quiz_question')
    op.drop_table('topic')
    op.drop_table('quiz')
    op.drop_table('question')
    op.drop_table('answer_option')
    # ### end Alembic commands ###
