"""Fix foreign key ambiguity for Question/AnswerOption

Revision ID: 5a15ac9e0c54
Revises: d6fa31f5d977
Create Date: 2026-01-31 20:50:01.815952

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5a15ac9e0c54'
down_revision = 'd6fa31f5d977'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('answer_option', schema=None) as batch_op:
        batch_op.create_foreign_key(None, 'question', ['question_id'], ['question_id'], ondelete='CASCADE')

    with op.batch_alter_table('question', schema=None) as batch_op:
        batch_op.create_foreign_key(None, 'answer_option', ['correct_answer_id'], ['answer_id'], ondelete='SET NULL')
        batch_op.create_foreign_key(None, 'topic', ['topic_id'], ['topic_id'], ondelete='CASCADE')

    with op.batch_alter_table('quiz_question', schema=None) as batch_op:
        batch_op.create_foreign_key(None, 'question', ['question_id'], ['question_id'])
        batch_op.create_foreign_key(None, 'quiz', ['quiz_id'], ['quiz_id'])

    with op.batch_alter_table('topic', schema=None) as batch_op:
        batch_op.create_foreign_key(None, 'topic', ['parent_topic'], ['topic_id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('topic', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')

    with op.batch_alter_table('quiz_question', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')

    with op.batch_alter_table('question', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')

    with op.batch_alter_table('answer_option', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')

    # ### end Alembic commands ###
