"""add new ComponentItem,SubscriptionPlan ,subscriptionPlan

Revision ID: ebb342c15139
Revises: ff7adcbbb590
Create Date: 2026-03-27 12:18:07.860321

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ebb342c15139'
down_revision = 'ff7adcbbb590'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('subscription_plans',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('plan_name', sa.String(length=255), nullable=False),
    sa.Column('no_quizzes', sa.Integer(), nullable=True),
    sa.Column('no_template_exams', sa.Integer(), nullable=True),
    sa.Column('no_topic_quizzes', sa.Integer(), nullable=True),
    sa.Column('duration_days', sa.Integer(), nullable=False),
    sa.Column('price', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('requests',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('plan_id', sa.Integer(), nullable=False),
    sa.Column('subscription_requested', sa.Boolean(), nullable=True),
    sa.Column('request_date', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['plan_id'], ['subscription_plans.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('subscriptions',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('plan_id', sa.Integer(), nullable=False),
    sa.Column('start_date', sa.DateTime(), nullable=True),
    sa.Column('expiry_date', sa.DateTime(), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=True),
    sa.Column('remaining_quizzes', sa.Integer(), nullable=True),
    sa.Column('remaining_template_exams', sa.Integer(), nullable=True),
    sa.Column('remaining_topic_quizzes', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['plan_id'], ['subscription_plans.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('answer_option', schema=None) as batch_op:
        batch_op.create_foreign_key(None, 'question', ['question_id'], ['question_id'], ondelete='CASCADE')

    with op.batch_alter_table('component_items', schema=None) as batch_op:
        batch_op.create_foreign_key(None, 'components', ['component_id'], ['component_id'])

    with op.batch_alter_table('components', schema=None) as batch_op:
        batch_op.create_foreign_key(None, 'sections', ['section_id'], ['section_id'])

    with op.batch_alter_table('question', schema=None) as batch_op:
        batch_op.create_foreign_key(None, 'topic', ['topic_id'], ['topic_id'], ondelete='CASCADE')
        batch_op.create_foreign_key(None, 'answer_option', ['correct_answer_id'], ['answer_id'], ondelete='SET NULL')

    with op.batch_alter_table('quiz_question', schema=None) as batch_op:
        batch_op.create_foreign_key(None, 'quiz', ['quiz_id'], ['quiz_id'])
        batch_op.create_foreign_key(None, 'question', ['question_id'], ['question_id'])

    with op.batch_alter_table('sections', schema=None) as batch_op:
        batch_op.create_foreign_key(None, 'topic', ['topic_id'], ['topic_id'])

    with op.batch_alter_table('topic', schema=None) as batch_op:
        batch_op.create_foreign_key(None, 'topic', ['parent_topic'], ['topic_id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('topic', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')

    with op.batch_alter_table('sections', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')

    with op.batch_alter_table('quiz_question', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')

    with op.batch_alter_table('question', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')

    with op.batch_alter_table('components', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')

    with op.batch_alter_table('component_items', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')

    with op.batch_alter_table('answer_option', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')

    op.drop_table('subscriptions')
    op.drop_table('requests')
    op.drop_table('subscription_plans')
    # ### end Alembic commands ###
